server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - https://nums-bank.vercel.app
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: https://auth-service-o3e7.onrender.com
          predicates:
            - Path=/api/auth/**

        - id: account-service
          uri: https://account-service-8kwx.onrender.com
          predicates:
            - Path=/api/accounts/**

        - id: transaction-service
          uri: https://transaction-service-khc7.onrender.com
          predicates:
            - Path=/api/transactions/**

        - id: loan-service
          uri: https://loan-service-gkpk.onrender.com
          predicates:
            - Path=/api/loans/**

        - id: admin-service
          uri: https://admin-service-9a29.onrender.com
          predicates:
            - Path=/api/admin/**